### ISSUE TITLE
meta / tasks / everything

### ISSUE THREAD

**Issue by ryankurte** [dist-svc/dsf#1]
## bugs / issues / improvements

- [ ] pages should be re-published on connection to new peers (handles bootstrap and new connection in one)
- [ ] service, peer, replica pages should be regenerated and published on expiry
- [ ] peers should support multiple addresses to mitigate the split-horizon problem
  - [ ] `net` impl will need to be somewhat routing-aware, prefer local and working addresses
- [ ] unreachable peers should be evicted from the DHT NodeTable to mitigate connectivity / search failures when the nearest set is entirely unreachable
  - [ ] upstream DHT impl should iterate to use the nearest _reachable_ subset
- [ ] constrained nodes should not be considered in viable DHT subsets

## meta

- [ ] core / store separation has not aged well, core needs a severe refactor / reduction
- [ ] separation between DSF and DHT concept of peers leads to some weird / complex behaviours, and makes improving DHT operations complex, might be worth merging these.
- [ ] private tertiary pages should contain a consistent hash to allow deduplication as the linked service information used otherwise is only available to authorised parties
